package com.rcdis.agent.entity;

import java.time.OffsetDateTime;

import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.annotation.Version;

import lombok.Getter;
import lombok.Setter;

/**
 * One row per Agent conversation.
 *
 * <p>{@code conversationId} is the client-visible identifier (a UUID generated by the frontend).
 * It is unique among non-deleted rows, so a browser refresh keeps pointing at the same server-side
 * session. Ownership is enforced in the service layer by comparing {@code userId} against the JWT
 * principal; identity is never taken from the request body.</p>
 */
@Getter
@Setter
@TableName("chat_session")
public class ChatSessionEntity extends BaseEntity {

    /** Client-visible conversation identifier, unique among non-deleted rows. */
    private String conversationId;
    /** Human-friendly title, derived from the first user message when the session is created. */
    private String title;
    /** Owner of the session; only this user may append to it. */
    private String userId;
    private String tenantId;
    /** Model provider code last used for this session; may change if the user picks another. */
    private String providerCode;
    /** {@code ACTIVE} while the session accepts new turns. */
    private String status;
    /** Cached count of non-deleted messages, avoids a full scan for the sidebar. */
    private Integer messageCount;
    private OffsetDateTime lastMessageAt;

    /** Rolling narrative summary of turns compressed out of the sliding window. */
    private String rollingSummary;
    /** Structured hard-facts (JSON) extracted from compressed turns; numbers kept verbatim. */
    private String summaryFacts;
    /** Largest chat_message.seq already covered by rollingSummary/summaryFacts. */
    private Integer summaryUptoSeq;
    private OffsetDateTime lastCompressedAt;
    private Integer compressCount;

    @Version
    private Integer version;
}
